// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcm41iD-Om8eNO4ySu578RYM8MzPQAFNE',
    appId: '1:422947212637:web:33d35555368deb9bb92cb4',
    messagingSenderId: '422947212637',
    projectId: 'shippingapp-71c75',
    authDomain: 'shippingapp-71c75.firebaseapp.com',
    storageBucket: 'shippingapp-71c75.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwJeTlzjPTEysThiUelUyl6c0WqjP6oeA',
    appId: '1:422947212637:android:9f88fe8d80ef7e4eb92cb4',
    messagingSenderId: '422947212637',
    projectId: 'shippingapp-71c75',
    storageBucket: 'shippingapp-71c75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpKPTOLC82D9AcMOdCGgSMWZ04s0rBv9A',
    appId: '1:422947212637:ios:d46faab85a7c87dab92cb4',
    messagingSenderId: '422947212637',
    projectId: 'shippingapp-71c75',
    storageBucket: 'shippingapp-71c75.appspot.com',
    iosBundleId: 'com.example.shippingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpKPTOLC82D9AcMOdCGgSMWZ04s0rBv9A',
    appId: '1:422947212637:ios:d46faab85a7c87dab92cb4',
    messagingSenderId: '422947212637',
    projectId: 'shippingapp-71c75',
    storageBucket: 'shippingapp-71c75.appspot.com',
    iosBundleId: 'com.example.shippingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcm41iD-Om8eNO4ySu578RYM8MzPQAFNE',
    appId: '1:422947212637:web:3c7fa894c703366bb92cb4',
    messagingSenderId: '422947212637',
    projectId: 'shippingapp-71c75',
    authDomain: 'shippingapp-71c75.firebaseapp.com',
    storageBucket: 'shippingapp-71c75.appspot.com',
  );
}
